version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --workers 4 --bind 0.0.0.0:8000 --timeout=300
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static:
  media:
