version: '3.8'

services:
  web:
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgres_data:
