version: '3'
services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - '.:/app'
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
